version: '3'

networks:
  fidor:
    external: true

services:

  # --- NGINX ---

  nginx:
    image: ${NGINX_DOCKER_IMAGE}
    ports:
      - '80:80'
      - "443:443"
    environment:
      - NGINX_HOST=${DOMAIN}
    volumes:
      - ${NGINX_VOLUME}/default.conf:/etc/nginx/conf.d/default.conf
    deploy:
      replicas: 1
    networks:
      - fidor
