version: '3'

networks:
  fidor:
    external: true

services:

  # --- NGINX ---

  nginx:
    image: ${NGINX_DOCKER_IMAGE}
    ports:
      - '80:80'
      - '443:443'
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      update_config:
        parallelism: 1
        delay: 3s
    volumes:
    - ${NGINX_VOLUME}/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - fidor
